name: Validator mot de passe Github
run-name: Test
on:
  push:
    branches: main
jobs:
  main:
    runs-on:
    steps:
      - name: Retrouver le code du repository
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: npm ci

      - name: Les tests sont lancés
        run: npm test

      - name: Build
        run: npm run build
